version: "3.4"

networks:
  proxylampy:
    external: true
  serverlampy:
    external: true
services:
  apache:
    networks:
      - net
      - proxylampy
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.wordpress.rule=Host(`wordpress.traefik.me`)"
        - "traefik.http.routers.wordpress-tls.tls.domains[0].main=wordpress.traefik.me"
        - "traefik.http.routers.wordpress.tls=true"
        - "traefik.http.services.wordpress.loadbalancer.server.port=80"
  phpfpm:
    networks:
      - net
      - serverlampy
