version: "3.4"
networks:
  net:
    driver: overlay
    attachable: true
  proxylampy:
    external: true
  serverlampy:
    external: true
services:
  www:
    image: koromerzhin/php:8.4.3-apache-symfony
    depends_on:
      - mariadb
      - mercure
      - mailhog
      - redis
    volumes:
      - ${PWD}/apps:/var/www/:rw
      - ${PWD}/conf/php.ini-development://usr/local/etc/php/conf.d/php.ini
      - ${PWD}/conf/apache2/000-default.conf:/etc/apache2/sites-available/000-default.conf:ro
      - ${PWD}/conf/apache2/apache2.conf:/etc/apache2/apache2.conf:ro
    environment:
      APP_SECRET: "CHANGEME"
      MAILER_DSN: "smtp://mailtest:1025"
      MESSENGER_TRANSPORT_DSN: "doctrine://default"
      LOCK_DNS: semaphore
      DATABASE_BDD: wordpress_bdd
      DATABASE_USER: wordpress
      DATABASE_PASSWORD: password
      DATABASE_URL: "mysqli://wordpress:password@mariadb:3306/wordpress_bdd"
    networks:
      - net
      - serverlampy
      - proxylampy
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.wordpress.rule=Host(`wordpress.traefik.me`)"
        - "traefik.http.routers.wordpress-tls.tls.domains[0].main=wordpress.traefik.me"
        - "traefik.http.routers.wordpress.tls=true"
        - "traefik.http.services.wordpress.loadbalancer.server.port=80"