version: "3.4"

networks:
  proxylampy:
    external: true
  serverlampy:
    external: true
  net:
    driver: overlay
    attachable: true

volumes:
  mariadb_data:

services:
  phpfpmexec:
    image: koromerzhin/phpfpm:8.1.6
    command: sh -c "composer install"
    volumes:
      - ${PWD}/apps:/var/www/
      - ${PWD}/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
    networks:
      - serverlampy
    depends_on:
      - mariadb
    deploy:
      restart_policy:
        condition: none
      labels:
        - "traefik.enable=false"
  apache:
    image: httpd:2.4.48
    depends_on:
      - phpfpm
    volumes:
      - ${PWD}/apps:/var/www/
      - ${PWD}/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
    networks:
      - net
      - proxylampy
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.wordpress.rule=Host(`wordpress.traefik.me`)"
        - "traefik.http.routers.wordpress-tls.tls.domains[0].main=wordpress.traefik.me"
        - "traefik.http.routers.wordpress.tls=true"
        - "traefik.http.services.wordpress.loadbalancer.server.port=80"
  phpfpm:
    image: koromerzhin/phpfpm:8.1.6
    depends_on:
      - mariadb
      - mailhog
    volumes:
      - ${PWD}/apps:/var/www/
      - ${PWD}/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
    networks:
      - net
      - serverlampy
    deploy:
      labels:
        - "traefik.enable=false"
