version: "3.4"

networks:
  proxynetwork:
    external: true
  net:
    driver: overlay
    attachable: true

volumes:
  mariadb_data:

services:
  mailhog:
    image: mailhog/mailhog
    networks:
      - net
      - proxynetwork
    depends_on:
      - proxynetwork
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.mailhog-wordpress.rule=Host(`mailhog-wordpress.traefik.me`)"
        - "traefik.http.routers.mailhog-wordpress-tls.tls.domains[0].main=mailhog-wordpress.traefik.me"
        - "traefik.http.routers.mailhog-wordpress-tls.tls.domains[0].sans=mailhog-wordpress-*.traefik.me"
        - "traefik.http.services.mailhog-wordpress.loadbalancer.server.port=8025"
  mariadb:
    image: mariadb:10.5.8
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: core
      MYSQL_USER: siteinternet
      MYSQL_PASSWORD: password
      TZ: Europe/Paris
    networks:
      - net
    deploy:
      labels:
        - "traefik.enable=false"
  apache:
    image: httpd
    depends_on:
      - phpfpm
    volumes:
      - ${PWD}/apps:/var/www/
      - ${PWD}/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
    networks:
      - net
      - proxynetwork
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.wordpress.rule=Host(`wordpress.traefik.me`)"
        - "traefik.http.routers.wordpress-tls.tls.domains[0].main=wordpress.traefik.me"
        - "traefik.http.routers.wordpress-tls.tls.domains[0].sans=wordpress-*.traefik.me"
        - "traefik.http.services.wordpress.loadbalancer.server.port=80"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: example
    depends_on:
      - mariadb
    networks:
      - net
      - proxynetwork
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.phpmyadmin-wordpress.rule=Host(`phpmyadmin-wordpress.traefik.me`)"
        - "traefik.http.routers.phpmyadmin-wordpress-tls.tls.domains[0].main=phpmyadmin-wordpress.traefik.me"
        - "traefik.http.routers.phpmyadmin-wordpress-tls.tls.domains[0].sans=phpmyadmin-wordpress-*.traefik.me"
        - "traefik.http.services.phpmyadmin-wordpress.loadbalancer.server.port=80"
  phpfpm:
    image: koromerzhin/phpfpm:7.4.12
    depends_on:
      - mariadb
      - mailhog
    volumes:
      - ${PWD}/apps:/var/www/
      - ${PWD}/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
    networks:
      - net
    deploy:
      labels:
        - "traefik.enable=false"
