version: 3

# Taskfile principal - Tâches globales et inclusions
# Charge automatiquement les variables depuis le fichier .env s'il existe
dotenv: [ '.env' ]

includes:
  docker: ./taskfiles/docker/Taskfile.yml
  utils: ./taskfiles/utils/Taskfile.yml
  env: ./taskfiles/env/Taskfile.yml
  nodejs: ./taskfiles/nodejs/Taskfile.yml
  download: ./taskfiles/download/Taskfile.yml
  apache: ./taskfiles/apache/Taskfile.yml

vars:
  # Variables avec valeurs par défaut depuis .env ou valeurs de fallback
  PROJECT_NAME: '{{.PROJECT_NAME | default "wordpress"}}'
  ENVIRONMENT: '{{.ENVIRONMENT | default "development"}}'
  STACK_NAME: '{{.STACK | default "wordpress"}}'
  FOLDERSQL: '{{.FOLDERSQL | default "database_init"}}'
  FILESQL: '{{.FILESQL | default "dump.sql"}}'
  FOLDERLAMPY: '{{.FOLDERLAMPY | default "lampy"}}'
  SERVERNAME: '{{.SERVERNAME | default "wordpress.traefik.me"}}'
  DOCKERCOMPOSEFILE: '{{.DOCKERCOMPOSEFILE | default "docker-compose-lampy.yml"}}'

tasks:
  default:
    desc: "Affiche l'aide et les tâches disponibles"
    silent: true
    cmds:
    - echo "🛠️  Collection de Taskfiles pour le développement"
    - echo ""
    - echo "Tâches globales disponibles :"
    - task --list
    - echo ""

  lint:all:
    desc: "Exécute tous les linters disponibles"
    cmds:
    - npm run lint:markdown

  info:
    desc: "Affiche les informations du projet avec les variables d'environnement"
    silent: true
    cmds:
    - |
      export PROJECT_VERSION=$(jq -r .version package.json)
      echo "🛠️  {{.PROJECT_NAME}} v$PROJECT_VERSION - Collection de Taskfiles"
      echo "Environnement: {{.ENVIRONMENT}}"

  help:
    desc: "Affiche l'aide détaillée"
    aliases: [ h ]
    silent: true
    cmds:
    - task: default

  create:apps:
    desc: "Crée le dossier apps avec une installation WordPress via Bedrock"
    silent: true
    cmds:
    - docker run --rm -v $(pwd):/var/www -w /var/www $(awk '/www:/ {f=1} f && /image:/ {print $2; exit}' {{.DOCKERCOMPOSEFILE}}) composer create-project roots/bedrock apps --no-interaction

  wordpress:getapacheconf:
    desc: "Récupère la configuration Apache depuis l'image Docker"
    silent: true
    cmds:
    - rm -rf ./conf/apache2 || true
    - mkdir -p ./conf/apache2
    - task docker:create CONTAINER_NAME=wordpress-php IMAGE_NAME=$(awk '/www:/ {f=1} f && /image:/ {print $2; exit}' {{.DOCKERCOMPOSEFILE}})
    - task: docker:getfile
      vars:
        CONTAINER_NAME: "wordpress-php"
        FILE_PATH: "/etc/apache2/sites-available/000-default.conf"
        DEST_PATH: "./conf/apache2/000-default.conf"
    - task: docker:getfile
      vars:
        CONTAINER_NAME: "wordpress-php"
        FILE_PATH: "/etc/apache2/apache2.conf"
        DEST_PATH: "./conf/apache2/apache2.conf"
    - docker rm -f wordpress-php
    - task: apache:updateconfig
      vars:
        SERVERNAME: "{{.SERVERNAME}}"
        APACHE_DOCUMENT_ROOT: "/var/www/web"

  wordpress:copysql:
    desc: "Copie le fichier SQL de dump dans le dossier wordpress"
    silent: true
    cmds:
    - task: utils:file:copy
      vars:
        SOURCE_FILE: ./{{.FOLDERSQL}}/{{.FILESQL}}
        DEST_DIR: "{{.FOLDERLAMPY}}/mariadb_init/"
        FORCE: true

  wordpress:getpull-image:
    desc: "Télécharge les images Docker définies dans le docker-compose.yml"
    silent: true
    cmds:
    - task: docker:images:pull
      vars:
        COMPOSE_FILE: "{{.DOCKERCOMPOSEFILE}}"

  wordpress:deploy:
    desc: "Déploie les stacks Docker définies dans les fichiers docker-compose"
    silent: true
    cmds:
    - task: docker:stack:deploy
      vars:
        COMPOSE_FILE: "{{.DOCKERCOMPOSEFILE}}"
        STACK_NAME: "{{.STACK_NAME}}"

  wordpress:waiting:
    desc: "Attend que les services soient opérationnels"
    silent: true
    cmds:
    - task: docker:stack:check:containers:ready
      vars:
        CONTAINERS: "www"
        STACK_NAME: "{{.STACK_NAME}}"

  wordpress:ls:
    desc: "Liste les stacks et services Docker"
    silent: true
    cmds:
    - task: docker:stack:services
      vars:
        STACK_NAME: "{{.STACK_NAME}}"

  wordpress:exec:
    desc: "Exécute une commande dans un conteneur en cours d'exécution"
    silent: true
    cmds:
    - task: wordpress:copysql
    - task: wordpress:getpull-image
    - task: wordpress:getapacheconf
    - task: create:apps
    - task: wordpress:deploy
    - task: wordpress:waiting
    - task: wordpress:ls

  wordpress:bash:
    desc: "Ouvre un shell bash dans le conteneur www"
    silent: true
    cmds:
    - task: docker:stack:shell
      vars:
        STACK_NAME: "wordpress"
        SERVICE_NAME: "www"

  wordpress:cmd-exec:
    desc: "Affiche les informations wordpress"
    silent: true
    vars:
      INTERACTIVE: '{{.INTERACTIVE | default "true"}}'
    cmds:
    - task: docker:stack:exec
      vars:
        STACK_NAME: "wordpress"
        SERVICE_NAME: "www"
        COMMAND: "{{.COMMAND}}"
        INTERACTIVE: "{{.INTERACTIVE}}"

  composer:exec:
    desc: "Exécute une commande Composer"
    silent: true
    vars:
      CMD: '{{.CMD | default ""}}'
    cmds:
    - task: wordpress:cmd-exec
      vars:
        COMMAND: "composer {{.CMD}}"

  composer:fund:
    desc: "Affiche les liens de financement des dépendances Composer"
    silent: true
    cmds:
    - task: composer:exec
      vars:
        CMD: "fund"

  composer:install:
    desc: "Installe les dépendances Composer"
    silent: true
    cmds:
    - task: composer:exec
      vars:
        CMD: "install"

  composer:outdated:
    desc: "Affiche les dépendances obsolètes"
    silent: true
    cmds:
    - task: composer:exec
      vars:
        CMD: "outdated"

  composer:suggests:
    desc: "Affiche les suggestions des dépendances Composer"
    silent: true
    cmds:
    - task: composer:exec
      vars:
        CMD: "suggests"

  composer:update:
    desc: "Met à jour les dépendances Composer"
    silent: true
    cmds:
    - task: composer:exec
      vars:
        CMD: "update"

  composer:validate:
    desc: "Valide le fichier composer.json"
    silent: true
    cmds:
    - task: composer:exec
      vars:
        CMD: "validate"

  composer:install:dev:
    desc: "Installe les dépendances Composer pour le développement"
    silent: true
    cmds:
    - task: composer:exec
      vars:
        CMD: "install --no-progress --prefer-dist --optimize-autoloader"

  composer:install:prod:
    desc: "Installe les dépendances Composer pour la production"
    silent: true
    cmds:
    - task: composer:exec
      vars:
        CMD: "install --no-progress --prefer-dist --optimize-autoloader --no-dev"
